### ISSUE TITLE
"What is Krieg Studios?" opens "Our Team"

### ISSUE THREAD

**Issue by islamhaqq** [KriegStudios/kriegstudios.com#1]
Instead of opening the "Our Team" section, it should just provide a text answer in the spoiler.

**Comment by MuhsinunC** [comment]
Like what? Text answer like what?

**Comment by islamhaqq** [comment]
@MuhsinunCool The two spoilers underneath "What is Krieg Studios" has text in it, but "What is Krieg Studios?" doesn't for some reason. Instead, when you click it, it redirects you to a section of the website without any text.
